"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("react");
var lucide_react_1 = require("lucide-react");
var react_router_dom_1 = require("react-router-dom");
var Footer = function () {
    var navigate = (0, react_router_dom_1.useNavigate)();
    return (react_1.default.createElement("footer", { className: "bg-slate-900 text-slate-300 pt-16 pb-8 border-t border-slate-800" },
        react_1.default.createElement("div", { className: "max-w-6xl mx-auto px-4" },
            react_1.default.createElement("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-12 mb-12" },
                react_1.default.createElement("div", null,
                    react_1.default.createElement("div", { className: "flex items-center gap-2 mb-6 text-white" },
                        react_1.default.createElement(lucide_react_1.Scale, { size: 32, className: "text-amber-500" }),
                        react_1.default.createElement("div", null,
                            react_1.default.createElement("h2", { className: "text-2xl font-serif font-bold leading-none" }, "JurisBlog"),
                            react_1.default.createElement("span", { className: "text-xs text-slate-500 tracking-widest uppercase" }, "Direito & Justi\u00E7a"))),
                    react_1.default.createElement("p", { className: "text-sm leading-relaxed text-slate-400 mb-6" }, "Comprometidos com a defesa dos seus direitos e a excel\u00EAncia jur\u00EDdica. Trazendo informa\u00E7\u00E3o clara e acess\u00EDvel para todos."),
                    react_1.default.createElement("div", { className: "flex gap-4 items-center" },
                        react_1.default.createElement("button", { className: "hover:text-amber-500 transition", title: "WhatsApp" },
                            react_1.default.createElement("svg", { viewBox: "0 0 24 24", width: "20", height: "20", stroke: "currentColor", strokeWidth: "2", fill: "none", strokeLinecap: "round", strokeLinejoin: "round", className: "lucide" },
                                react_1.default.createElement("path", { d: "M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" }))),
                        react_1.default.createElement("button", { className: "hover:text-amber-500 transition" },
                            react_1.default.createElement(lucide_react_1.Instagram, { size: 20 })),
                        react_1.default.createElement("button", { className: "hover:text-amber-500 transition", title: "TikTok" },
                            react_1.default.createElement("svg", { viewBox: "0 0 24 24", width: "20", height: "20", fill: "currentColor", className: "block" },
                                react_1.default.createElement("path", { d: "M12.525.02c1.31-.02 2.61-.01 3.91-.02.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97-.57-.26-1.1-.65-1.62-1.12v8.76c0 5.29-5.43 7.31-9.65 5.71-2.73-1.04-4.22-3.83-3.79-6.67.31-2.06 1.76-3.83 3.73-4.59 1.94-.78 4.2-.39 5.86.87V6.53c-.77-.29-1.59-.47-2.42-.47-3.32.06-6.04 2.81-6.04 6.15 0 3.31 2.65 6.01 5.96 6.09 3.25.08 6.01-2.5 6.03-5.75L16.29 6h-3.76l-.005-5.98z" }))),
                        react_1.default.createElement("button", { className: "hover:text-amber-500 transition" },
                            react_1.default.createElement(lucide_react_1.Facebook, { size: 20 })),
                        react_1.default.createElement("button", { className: "hover:text-amber-500 transition" },
                            react_1.default.createElement(lucide_react_1.Linkedin, { size: 20 })))),
                react_1.default.createElement("div", null,
                    react_1.default.createElement("h3", { className: "text-white font-bold mb-6 border-b border-slate-700 pb-2 inline-block" }, "Navega\u00E7\u00E3o"),
                    react_1.default.createElement("ul", { className: "space-y-3 text-sm" },
                        react_1.default.createElement("li", null,
                            react_1.default.createElement("button", { onClick: function () { return navigate('/'); }, className: "hover:text-amber-500 transition flex items-center gap-2" }, "In\u00EDcio")),
                        react_1.default.createElement("li", null,
                            react_1.default.createElement("button", { onClick: function () { return navigate('/sobre'); }, className: "hover:text-amber-500 transition flex items-center gap-2" }, "Sobre o Escrit\u00F3rio")),
                        react_1.default.createElement("li", null,
                            react_1.default.createElement("button", { onClick: function () { return navigate('/contato'); }, className: "hover:text-amber-500 transition flex items-center gap-2" }, "Fale Conosco")),
                        react_1.default.createElement("li", null,
                            react_1.default.createElement("button", { onClick: function () { return navigate('/admin'); }, className: "hover:text-amber-500 transition flex items-center gap-2 text-amber-600 font-bold" }, "\u00C1rea do Advogado")))),
                react_1.default.createElement("div", null,
                    react_1.default.createElement("h3", { className: "text-white font-bold mb-6 border-b border-slate-700 pb-2 inline-block" }, "Contatos"),
                    react_1.default.createElement("ul", { className: "space-y-4 text-sm" },
                        react_1.default.createElement("li", { className: "flex items-start gap-3" },
                            react_1.default.createElement(lucide_react_1.MapPin, { size: 18, className: "text-amber-500 mt-1 shrink-0" }),
                            react_1.default.createElement("span", null,
                                "Av. Paulista, 1000 - Bela Vista",
                                react_1.default.createElement("br", null),
                                "S\u00E3o Paulo - SP, 01310-100")),
                        react_1.default.createElement("li", { className: "flex items-center gap-3" },
                            react_1.default.createElement(lucide_react_1.Phone, { size: 18, className: "text-amber-500 shrink-0" }),
                            react_1.default.createElement("span", null, "(11) 9999-9999")),
                        react_1.default.createElement("li", { className: "flex items-center gap-3" },
                            react_1.default.createElement(lucide_react_1.Mail, { size: 18, className: "text-amber-500 shrink-0" }),
                            react_1.default.createElement("span", null, "contato@juris.com"))))),
            react_1.default.createElement("div", { className: "border-t border-slate-800 pt-8 flex flex-col md:flex-row justify-between items-center text-xs text-slate-500" },
                react_1.default.createElement("p", null,
                    "\u00A9 ",
                    new Date().getFullYear(),
                    " JurisBlog Advogados Associados. Todos os direitos reservados."),
                react_1.default.createElement("div", { className: "flex gap-6 mt-4 md:mt-0" },
                    react_1.default.createElement("span", null, "OAB/SP 123.456"),
                    react_1.default.createElement("span", { className: "hover:text-slate-300 cursor-pointer" }, "Termos de Uso"),
                    react_1.default.createElement("span", { className: "hover:text-slate-300 cursor-pointer" }, "Privacidade"))))));
};
exports.default = Footer;
//# sourceMappingURL=Footer.js.map